@startuml!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.pumlPerson(user, "Пользователь", "Владелец дома, управляет отоплением и следит за состоянием системы")Person(tech, "Специалист по установке", "Выездной сотрудник, подключающий датчики и реле")System(system, "Монолитное приложение 'Тёплый дом'", "Go-приложение с PostgreSQL, выполняющее управление отоплением")System_Ext(sensors, "Датчики и модули управления", "Устройства, установленные в домах клиентов")System_Ext(support, "Служба поддержки", "Команда, работающая с обращениями пользователей")Rel(user, system, "Изменяет режимы отопления, просматривает температуру", "Веб-клиент")Rel(system, sensors, "Запрашивает температуру и отправляет команды", "Синхронный запрос по протоколам производителей")Rel(tech, system, "Настраивает и регистрирует устройства", "Административные инструменты")Rel(support, system, "Получает информацию о клиентах и показаниях", "Внутренний интерфейс")@enduml